"""Remove unique in status purchase

Revision ID: a6eac9be1e2f
Revises: b0c3dd0f3434
Create Date: 2020-12-11 20:10:32.286108

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "a6eac9be1e2f"
down_revision = "b0c3dd0f3434"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_purchase_status", table_name="purchase")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index("ix_purchase_status", "purchase", ["status"], unique=True)
    # ### end Alembic commands ###
