"""Added purchase table

Revision ID: d8724a5e7b34
Revises: 22794c70fe7e
Create Date: 2020-12-10 03:30:52.454292

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "d8724a5e7b34"
down_revision = "22794c70fe7e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "purchase",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("uuid", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("code", sa.String(), nullable=False),
        sa.Column("value", sa.Numeric(), nullable=False),
        sa.Column("purchase_date", sa.DateTime(), nullable=True),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("cashback_percente", sa.Float(), nullable=True),
        sa.Column("cashback_value", sa.Numeric(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("uuid"),
    )
    op.create_index(op.f("ix_purchase_code"), "purchase", ["code"], unique=True)
    op.create_index(op.f("ix_purchase_status"), "purchase", ["status"], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_purchase_status"), table_name="purchase")
    op.drop_index(op.f("ix_purchase_code"), table_name="purchase")
    op.drop_table("purchase")
    # ### end Alembic commands ###
